In [8]:
import random
p = 0.7
num = random.random()
if num < 0.7:
    print(num, 1)
else:
    print(num, 0)

0.40514321303873246 1


In [10]:
import numpy as np
x = np.array([1, 2, 3, 4])
print(x)
x = x.reshape((2,2))
print(x)

[1 2 3 4]
[[1 2]
 [3 4]]


In [11]:
x = random.random()
print(x, x < 0.5)

0.3225241323953727 True


In [14]:
print(int(False))

0


In [16]:
print('\u2520')

┠


In [17]:
print({'u250F': '\u250F', 'u2501': '\u2501', 'u252F': '\u252F',
           'u2513': '\u2513', 'u2520': '\u2520', 'u2500': '\u2500',
           'u253C': '\u253C', 'u2528': '\u2528', 'u2517': '\u2517',
           'u2537': '\u2537', 'u251B': '\u252B', 'u2503': '\u2503',
           'u2502': '\u2502', 'u2588': '\u2588'})

{'u250F': '┏', 'u2501': '━', 'u252F': '┯', 'u2513': '┓', 'u2520': '┠', 'u2500': '─', 'u253C': '┼', 'u2528': '┨', 'u2517': '┗', 'u2537': '┷', 'u251B': '┫', 'u2503': '┃', 'u2502': '│', 'u2588': '█'}


In [19]:
import pprint
x = np.array([1, 2, 3, 4, 5, 6]).reshape(3, 2)
pprint.pprint(x)

array([[1, 2],
       [3, 4],
       [5, 6]])


In [20]:
print(len(x[0]))

2


In [27]:
import itertools
print(list(itertools.chain(*[[1, 2, 3, 4], [5, 6, 7, 8]])))
print(list(itertools.chain([1, 2, 3, 4], [5, 6, 7, 8])))

[1, 2, 3, 4, 5, 6, 7, 8]
[1, 2, 3, 4, 5, 6, 7, 8]


In [25]:
print(*[1, 2, 3, 4])

1 2 3 4


In [28]:
list(zip([1, 2, 3, 4], ['a', 'b', 'c', 'd']))

[(1, 'a'), (2, 'b'), (3, 'c'), (4, 'd')]

In [35]:
line = ['\u2501']*4
jn = ['\u252F']*4
print(line)
print(jn)
print(list(zip(line, jn)))
print(list(itertools.chain(*list(zip(line, jn)))))

['━', '━', '━', '━']
['┯', '┯', '┯', '┯']
[('━', '┯'), ('━', '┯'), ('━', '┯'), ('━', '┯')]
['━', '┯', '━', '┯', '━', '┯', '━', '┯']


In [39]:
from colorama import Fore
print(Fore.BLUE + 'abcde')

abcde


In [42]:
CHAR_COLOR_MAP = {'BLOCKED': {'char': 0, 'color': Fore.RED},
                  'OPEN': {'char': 1, 'color': Fore.YELLOW}}
print(CHAR_COLOR_MAP)

{'BLOCKED': {'char': 0, 'color': '\x1b'}, 'OPEN': {'char': 1, 'color': '\x1b'}}


In [3]:
import numpy as np
for index in np.arange(0.1, 0.9, 0.05):
    print(index)

0.1
0.15
0.2
0.25
0.3
0.35
0.4
0.45
0.5
0.55
0.6
0.65
0.7
0.75
0.8
0.85
